### ISSUE TITLE
Neuropixels 2.0 support

### ISSUE THREAD

**Issue by AntonioST** [NeuralEnsemble/python-neo#1028]
Hi all,

I recently used spikeinterface to preprocess my 4-shank neuropixels 2 data, but got a `ZeroDivisionError`.

```
Traceback (most recent call last):
  File ".../script_car.py", line 24, in <module>
    recording = se.read_spikeglx(data_file.parent, 'imec0.ap')
  File ".../spikeinterface/extractors/neoextractors/spikeglx.py", line 39, in read_spikeglx
    recording = SpikeGLXRecordingExtractor(*args, **kwargs)
  File ".../spikeinterface/extractors/neoextractors/spikeglx.py", line 29, in __init__
    NeoBaseRecordingExtractor.__init__(self, stream_id=stream_id, **neo_kwargs)
  File ".../spikeinterface/extractors/neoextractors/neobaseextractor.py", line 26, in __init__
    _NeoBaseExtractor.__init__(self, **neo_kwargs)
  File ".../spikeinterface/extractors/neoextractors/neobaseextractor.py", line 16, in __init__
    self.neo_reader.parse_header()
  File ".../neo/rawio/baserawio.py", line 185, in parse_header
    self._parse_header()
  File ".../neo/rawio/spikeglxrawio.py", line 67, in _parse_header
    self.signals_info_list = scan_files(self.dirname)
  File ".../neo/rawio/spikeglxrawio.py", line 238, in scan_files
    per_channel_gain[c] = 1. / float(meta['imroTbl'][c].split(' ')[index_imroTbl])
ZeroDivisionError: float division by zero
```
According to the document from [SpikeGlx](https://billkarsh.github.io/SpikeGLX/help/imroTables/), the `AP band gain` and `LF band gain` value are not existed in  Neuropixels 2.0 (type 21 and 24).

**Comment by samuelgarcia** [comment]
Hi @AntonioST.
Coudl you send us a small folder with the new "meta" file and a very short version of the "bin".
So I could implement it.

**Comment by AntonioST** [comment]
Hi,

Here the attachment I use empty probe to record 1 second.

[TEST_20210920_0_g0.tar.gz](https://github.com/NeuralEnsemble/python-neo/files/7195567/TEST_20210920_0_g0.tar.gz)

**Comment by samuelgarcia** [comment]
Thank you very much.
I guess you agree that this file will be public and avaliable here : https://gin.g-node.org/NeuralEnsemble/ephy_testing_data

**Comment by AntonioST** [comment]
Yes.

**Comment by AntonioST** [comment]
1. Sorry I don't have 1 shank NP2 files now.
2. the distance between the shanks is 250 um.
