### ISSUE TITLE
Using `*.append` doesn't check input type

### ISSUE THREAD

**Issue by Helveg** [NeuralEnsemble/python-neo#1201]
**Describe the bug**
The inputs to functions that accept only objects of a specific type, such as `.segments.append` or `.analogsignals.append`, are not checked and more cryptic errors are encountered downstream:

```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pwd06\git\bsb\bsb\__main__.py", line 3, in <module>
    cli.handle_cli()
  File "C:\Users\pwd06\git\bsb\bsb\cli\__init__.py", line 10, in handle_cli
    handle_command(sys.argv[1:], exit=True)
  File "C:\Users\pwd06\git\bsb\bsb\cli\__init__.py", line 30, in handle_command
    namespace.handler(namespace, dryrun=dryrun)
  File "C:\Users\pwd06\git\bsb\bsb\cli\commands\__init__.py", line 97, in execute_handler
    self.handler(context)
  File "C:\Users\pwd06\git\bsb\bsb\cli\commands\_commands.py", line 210, in handler
    result.write(f"{uuid4()}.nio", "ow")
  File "C:\Users\pwd06\git\bsb\bsb\simulation\results.py", line 38, in write
    io.NixIO(filename, mode=mode).write(self.block)
  File "C:\Users\pwd06\erice2022\lib\site-packages\neo\io\baseio.py", line 142, in write
    self.write_block(bl, **kargs)
  File "C:\Users\pwd06\erice2022\lib\site-packages\neo\io\nixio.py", line 645, in write_block
    self._write_segment(seg, nixblock)
  File "C:\Users\pwd06\erice2022\lib\site-packages\neo\io\nixio.py", line 733, in _write_segment
    self._write_analogsignal(asig, nixblock, nixgroup)
  File "C:\Users\pwd06\erice2022\lib\site-packages\neo\io\nixio.py", line 836, in _write_analogsignal
    if "nix_name" in anasig.annotations:
AttributeError: 'list' object has no attribute 'annotations'
```

**To Reproduce**
Append a `list` to `segment.analogsignals`:

```
segment.analogsignals.append([1,3,-4,5])
```

If the error occurs when reading a file that you can't share publicly, please let us know, and we'll get in touch to discuss sharing it privately.

**Expected behaviour**

It is relatively easy to forget to wrap your analog signal in an `AnalogSignal`, and I'd expect this to throw an error a la:

```
Object of type 'list' is not an 'AnalogSignal'
```

**Comment by JuliaSprenger** [comment]
See also #125

**Comment by zm711** [comment]
This error has been fixed. Now when appending things like `list` an appropriate error comes up.

```
for seg in block.segments:
...     seg.analogsignals.append([1,2,3]) # list is not an analogsignal
```

```
TypeError: Object is a <class 'list'>. It should be one of (<class 'neo.core.analogsignal.AnalogSignal'>,).
>>> 
```
