### ISSUE TITLE
Cannot load SpikeGLX recording without `snsMnMaXaDw`

### ISSUE THREAD

**Issue by DradeAW** [NeuralEnsemble/python-neo#1240]
Hi,

I'm trying to load a SpikeGLX recording, but I'm getting the following error:

```python
import neo

io = neo.rawio.SpikeGLXRawIO(".")
io.parse_header()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home1/users/nsr/wyngaard/dev/python-neo/neo/rawio/baserawio.py", line 179, in parse_header
    self._parse_header()
  File "/export/home1/users/nsr/wyngaard/dev/python-neo/neo/rawio/spikeglxrawio.py", line 86, in _parse_header
    self.signals_info_list = scan_files(self.dirname)
  File "/export/home1/users/nsr/wyngaard/dev/python-neo/neo/rawio/spikeglxrawio.py", line 259, in scan_files
    info = extract_stream_info(meta_filename, meta)
  File "/export/home1/users/nsr/wyngaard/dev/python-neo/neo/rawio/spikeglxrawio.py", line 420, in extract_stream_info
    mn, ma, xa, dw = [int(e) for e in meta['snsMnMaXaDw'].split(sep=',')]
KeyError: 'snsMnMaXaDw'
```

I'm on the newest version of neo (the development version) on Ubuntu 20.04.

**Comment by samuelgarcia** [comment]
Oups.
Do you have the meta file for this ?

**Comment by DradeAW** [comment]
Here it is:
https://hub.bio.ens.psl.eu/index.php/s/DSt42eTG5dtqRp8

**Comment by samuelgarcia** [comment]
Salut Aurlien.
The main reason is the the filename is breaking a bit the convention.
`02.221128_2023-03-10_g0_tcat.imec0.ap.meta` you have an extra dot at the begnning after `02.`
but the dot is used as a field separator to detect `imec0` and `ap`.

I can make a small patch to improve this.
