### ISSUE TITLE
Error in PlexonIO

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/python-neo#188]
```
$ nosetests neo/test/iotest/test_plexonio.py:TestPlexonIO
E...E.
======================================================================
ERROR: test_assert_readed_neo_object_is_compliant (neo.test.iotest.test_plexonio.TestPlexonIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andrew/dev/neo/neo/test/iotest/common_io_test.py", line 499, in test_assert_readed_neo_object_is_compliant
    return_path=True):
  File "/Users/andrew/dev/neo/neo/test/iotest/tools.py", line 420, in iter_read_objects
    obj = obj_reader(cascade=cascade, lazy=lazy)
  File "/Users/andrew/dev/neo/neo/io/plexonio.py", line 249, in read_segment
    labels=evarrays[chan]['labels'],
UnboundLocalError: local variable 'evarrays' referenced before assignment

======================================================================
ERROR: test_readed_with_lazy_is_compliant (neo.test.iotest.test_plexonio.TestPlexonIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andrew/dev/neo/neo/test/iotest/common_io_test.py", line 539, in test_readed_with_lazy_is_compliant
    return_path=True):
  File "/Users/andrew/dev/neo/neo/test/iotest/tools.py", line 420, in iter_read_objects
    obj = obj_reader(cascade=cascade, lazy=lazy)
  File "/Users/andrew/dev/neo/neo/io/plexonio.py", line 249, in read_segment
    labels=evarrays[chan]['labels'],
UnboundLocalError: local variable 'evarrays' referenced before assignment

----------------------------------------------------------------------
Ran 6 tests in 5.337s

FAILED (errors=2)
```

**Comment by samuelgarcia** [comment]
Close by PR #190.
