### ISSUE TITLE
UnicodeDecodeError while opening BrainVision EEG files

### ISSUE THREAD

**Issue by akshaybabloo** [NeuralEnsemble/python-neo#238]
Hi,

I am trying to open BrainVision EEG file and I get an error as follows

```
Traceback (most recent call last):
  File "/Users/akshayrajgollahalli/Box Sync/MyDrive/Projects/Akshay-GitHub/Machine-Learning/Spiking-Neural-Network/Spike-Encoding/main2.py", line 14, in <module>
    seg = r.read_segment(lazy = False, cascade = True,)
  File "/Users/akshayrajgollahalli/anaconda/lib/python3.4/site-packages/neo/io/brainvisionio.py", line 69, in read_segment
    header = readBrainSoup(self.filename)
  File "/Users/akshayrajgollahalli/anaconda/lib/python3.4/site-packages/neo/io/brainvisionio.py", line 147, in readBrainSoup
    for line in open(filename , 'rU'):
  File "/Users/akshayrajgollahalli/anaconda/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 2: invalid start byte
```

Any idea on what's going on?

**Comment by samuelgarcia** [comment]
Fixed by #385.
