### ISSUE TITLE
import neo fails

### ISSUE THREAD

**Issue by MRIO** [NeuralEnsemble/python-neo#264]
Greetings,

I fail to import neo -- apparently some shenanigan with the version of quantities.  I have brew python in Sierra and the latest attached pip.

A cursory google did not return in spades, so i reach for help here.

I've installed neo 0.4.1 with pip, and pip check returns:

```
pip check                                                                                         [3778]
neo 0.4.1 has requirement quantities>=0.9.0, but you have quantities 0+unknown.
-1- M@Behemoth NML/olive_tree % pip install quantities                                                                        

Requirement already satisfied: quantities in /usr/local/lib/python2.7/site-packages

```

And this is the result of 'import neo'

---
```


Python 2.7.11 (default, Nov  6 2016, 23:39:22)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin

>>> import neo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/neo/__init__.py", line 11, in <module>
    from neo.core import *
  File "/usr/local/lib/python2.7/site-packages/neo/core/__init__.py", line 39, in <module>
    from neo.core.recordingchannel import RecordingChannel
  File "/usr/local/lib/python2.7/site-packages/neo/core/recordingchannel.py", line 13, in <module>
    import quantities as pq
  File "/usr/local/lib/python2.7/site-packages/quantities/__init__.py", line 276, in <module>
    from . import quantity
  File "/usr/local/lib/python2.7/site-packages/quantities/quantity.py", line 113, in <module>
    class Quantity(np.ndarray):
  File "/usr/local/lib/python2.7/site-packages/quantities/quantity.py", line 617, in Quantity
    @with_doc(np.nanmean)
AttributeError: 'module' object has no attribute 'nanmean'
>>>
```

Is this known?

**Comment by apdavison** [comment]
It looks as though your `numpy` version is too old. The `numpy.nanmean` function was introduced in NumPy 1.8. What version do you have?

**Comment by MRIO** [comment]
Yep, the brew bundled version was 1.7 -- just updated and it loads smoothly. Thanks for the flash response!
