### ISSUE TITLE
unit with a name containing a slash cannot be read slash (/) 

### ISSUE THREAD

**Issue by schmitts** [NeuralEnsemble/python-neo#306]
Using NixIO from neo 0.5.0, reading a unit with a slash (/) in its name leads to an error:

```python
#!/usr/bin/env python

from neo import *

blk = Block()

# add a unit with a '/' in its name
unit = Unit(name="foo/bar")
chx = ChannelIndex([0])
chx.units.append(unit)
blk.channel_indexes.append(chx)

NixIO(filename="blk.h5", mode='ow').write(blk)

# fails: AttributeError: 'NixIO' object has no attribute 'read_fo'
NixIO(filename="blk.h5")
```

```
Traceback (most recent call last):
  File "./test_slash_in_name.py", line 13, in <module>
    NixIO(filename="blk.h5", mode='ow').write(blk)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/baseio.py", line 136, in write
    self.write_block(bl, **kargs)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 595, in write_block
    self._write_object(bl, loc)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 547, in _write_object
    self._write_cascade(obj, objpath)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 736, in _write_cascade
    write_func(ch, path)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 606, in write_channelindex
    self._write_object(chx, loc)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 547, in _write_object
    self._write_cascade(obj, objpath)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 736, in _write_cascade
    write_func(ch, path)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 718, in write_unit
    self._write_object(ut, loc)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 527, in _write_object
    oldobj = self.get(objpath, cascade=False, lazy=False)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 483, in get
    read_func = getattr(self, "read_" + neotype)
AttributeError: 'NixIO' object has no attribute 'read_fo'
```

**Comment by achilleas-k** [comment]
HDF5 uses `/` as a delimiter for groups, which it uses as an analogue to directories. The correct behaviour here should be for the NixIO to fail to save an object with a `/` in the name, since NIX considers such names invalid.

The strange error message (`read_fo`) is due to the way the NixIO expects slashes are a group delimiter and uses it to split HDF5 path strings to determine the type of the object being read.

I believe the HDF5 spec does not allow slashes in names to begin with (perhaps some HDF5 libraries do, but they shouldn't), so the solution here, as I already mentioned, is to throw an exception when an object with a slash in the name is encountered. I wonder, however, whether the NixIO should sanitize names and perhaps replace the `/` with another character (perhaps `|` or `_`)?
