### ISSUE TITLE
empty SpikeTrain causes integer division or modulo by zero

### ISSUE THREAD

**Issue by schmitts** [NeuralEnsemble/python-neo#308]
with neo 0.5.0:

```python
#!/usr/bin/env python

from neo import *
from quantities import ms, mV

blk = Block()
seg = Segment()
blk.segments.append(seg)

# empty spike times
train = SpikeTrain(times=[]*ms,t_stop=1*ms)
seg.spiketrains.append(train)

NixIO(filename="blk.h5", mode='ow').write(blk)
NixIO(filename="blk.h5").read_block()
```

```
Traceback (most recent call last):
  File "./test_spiketrain_empty.py", line 15, in <module>
    NixIO(filename="blk.h5").read_block()
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 146, in read_block
    self._read_cascade(nix_block, path, cascade, lazy)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 445, in _read_cascade
    for cp in chpaths)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 445, in <genexpr>
    for cp in chpaths)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 155, in read_segment
    self._read_cascade(nix_group, path, cascade, lazy)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 445, in _read_cascade
    for cp in chpaths)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 445, in <genexpr>
    for cp in chpaths)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 225, in read_spiketrain
    return self.read_eest(path, lazy)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 210, in read_eest
    neo_eest = self._mtag_eest_to_neo(nix_mtag, lazy)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-neo-0.5.0-wxd2ru2f6ezgnmdmbjh2uft3qubp4bst/lib/python2.7/site-packages/neo-0.5.0-py2.7.egg/neo/io/nixio.py", line 345, in _mtag_eest_to_neo
    times = pq.Quantity(nix_mtag.positions, time_unit)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-quantities-0.11.1-jcosbybdywouypmxqkr6dgwqox5cxuzm/lib/python2.7/site-packages/quantities/quantity.py", line 126, in __new__
    ret = np.array(data, dtype=dtype, copy=copy).view(cls)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-nixpy-1.3.0-2imwpbuhlzmyl3p2y3ydp46p6f53umlq/lib/python2.7/site-packages/nixio-1.3.0-py2.7-linux-x86_64.egg/nixio/data_array.py", line 120, in __array__
    self.read_direct(raw)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-nixpy-1.3.0-2imwpbuhlzmyl3p2y3ydp46p6f53umlq/lib/python2.7/site-packages/nixio-1.3.0-py2.7-linux-x86_64.egg/nixio/data_array.py", line 224, in read_direct
    self._read_data(data, (), ())
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-nixpy-1.3.0-2imwpbuhlzmyl3p2y3ydp46p6f53umlq/lib/python2.7/site-packages/nixio-1.3.0-py2.7-linux-x86_64.egg/nixio/pycore/data_array.py", line 83, in _read_data
    super(DataArray, self)._read_data(data, count, offset)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-nixpy-1.3.0-2imwpbuhlzmyl3p2y3ydp46p6f53umlq/lib/python2.7/site-packages/nixio-1.3.0-py2.7-linux-x86_64.egg/nixio/pycore/data_array.py", line 30, in _read_data
    dataset.read_data(data, count, offset)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-nixpy-1.3.0-2imwpbuhlzmyl3p2y3ydp46p6f53umlq/lib/python2.7/site-packages/nixio-1.3.0-py2.7-linux-x86_64.egg/nixio/pycore/h5dataset.py", line 57, in read_data
    self.dataset.read_direct(data)
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-h5py-2.6.0-w2dm5l3glp4q3zk2hgixiwwkv3d5ce7j/lib/python2.7/site-packages/h5py-2.6.0-py2.7-linux-x86_64.egg/h5py/_hl/dataset.py", line 640, in read_direct
    for mspace in dest_sel.broadcast(source_sel.mshape):
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-h5py-2.6.0-w2dm5l3glp4q3zk2hgixiwwkv3d5ce7j/lib/python2.7/site-packages/h5py-2.6.0-py2.7-linux-x86_64.egg/h5py/_hl/selections.py", line 301, in broadcast
    chunks = tuple(x//y for x, y in zip(count, tshape))
  File "/wang/environment/software/jessie/spack/2017-01-26/opt/spack/linux-debian8-x86_64/gcc-4.9.2/py-h5py-2.6.0-w2dm5l3glp4q3zk2hgixiwwkv3d5ce7j/lib/python2.7/site-packages/h5py-2.6.0-py2.7-linux-x86_64.egg/h5py/_hl/selections.py", line 301, in <genexpr>
    chunks = tuple(x//y for x, y in zip(count, tshape))
ZeroDivisionError: integer division or modulo by zero
```

**Comment by achilleas-k** [comment]
This is an issue with how h5py handles empty datasets and it affects nixpy (which in turn affects the NIXIO). I came across it a few weeks ago and I have a fix in my development branch (https://github.com/achilleas-k/nixpy/commit/79fa1a555fc6d884ae7811f516531ba69a6b9273) but I hadn't merged since I'm still working on some other fixes.

Since this has come up, I'll make a quick release with this fix only.

**Comment by achilleas-k** [comment]
A fix has now been merged into nixpy master (https://github.com/G-Node/nixpy/commit/8140ff15ba5a88dbfb5aad24cc10b3a1e0af9caf) and will be resolved in the next release.

**Comment by apdavison** [comment]
Tested by @legouee with the most recent nixpy, no error messages.
