### ISSUE TITLE
BlackrockIO: faulty code path hides file-not-found error.

### ISSUE THREAD

**Issue by cboulay** [NeuralEnsemble/python-neo#480]
Currently if you try

```Python
from neo.io import BlackrockIO
reader = BlackrockIO(filename='incorrect file name.ns6')

Traceback (most recent call last):
  File "/home/chad/miniconda3/envs/np/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-6d8e9f1dfa9e>", line 1, in <module>
    reader = BlackrockIO(filename='nonsense')
  File "/home/chad/miniconda3/envs/np/lib/python3.5/site-packages/neo/io/blackrockio.py", line 16, in __init__
    BaseFromRaw.__init__(self, filename)
  File "/home/chad/miniconda3/envs/np/lib/python3.5/site-packages/neo/io/basefromrawio.py", line 72, in __init__
    self.parse_header()
  File "/home/chad/miniconda3/envs/np/lib/python3.5/site-packages/neo/rawio/baserawio.py", line 154, in parse_header
    self._parse_header()
  File "/home/chad/miniconda3/envs/np/lib/python3.5/site-packages/neo/rawio/blackrockrawio.py", line 366, in _parse_header
    for k, data in self.nev_data.items():
AttributeError: 'BlackrockIO' object has no attribute 'nev_data'
```

This identifies a faulty code path, in which `self.nev_data` is never assigned because the '.nev' file is not found, and then later the search for nsx files depends on the presence of `self.nev_data`. This would be a problem if you had a data directory with nsx files but no .nev file.

I think nsx loading shouldn't depend on the presence of a .nev file.

I also think a more informative error message is needed when no matching files of any extension are found.

**Comment by samuelgarcia** [comment]
I agree this is a bug. This IO should work without nev files.
I will fix it.

**Comment by samuelgarcia** [comment]
Close by #482.
