### ISSUE TITLE
Master broken

### ISSUE THREAD

**Issue by samuelgarcia** [NeuralEnsemble/python-neo#518]
@JuliaSprenger @apdavison @bjoern1001001 
The master branch do not pass tests because of a pretty print in Epoch.
I don't remember who play with the print recently ?

We have to fix it before other PR because they all fail for py36 but not for py27.
Any idea ?

```
======================================================================
FAIL: test__pretty (neo.test.coretest.test_epoch.TestEpoch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/repo/neo/test/coretest/test_epoch.py", line 230, in test__pretty
    self.assertEqual(prepr, targ)
AssertionError: '<Epoch: test epoch 1@1.1 ms for 20.0 ns,[62 chars] ns>' != "Epoch\nname: 'test'\ndescription: 'teste[44 chars] 2]}"
- <Epoch: test epoch 1@1.1 ms for 20.0 ns, test epoch 2@1.5 ms for 40.0 ns, test epoch 3@1.7 ms for 60.0 ns>
+ Epoch
name: 'test'
description: 'tester'
annotations: {'test1': 1.1, 'test0': [1, 2]}


======================================================================
FAIL: test__pretty (neo.test.coretest.test_event.TestEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/repo/neo/test/coretest/test_event.py", line 372, in test__pretty
    self.assertEqual(prepr, targ)
AssertionError: '<Event: test event 1@1.1 ms, test event [26 chars] ms>' != "Event\nname: 'test'\ndescription: 'teste[44 chars] 2]}"
- <Event: test event 1@1.1 ms, test event 2@1.5 ms, test event 3@1.7 ms>
+ Event
name: 'test'
description: 'tester'
annotations: {'test1': 1.1, 'test0': [1, 2]}


======================================================================
FAIL: test__pretty (neo.test.coretest.test_spiketrain.TestPropertiesMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/repo/neo/test/coretest/test_spiketrain.py", line 1699, in test__pretty
    self.assertEqual(res, targ)
AssertionError: '<SpikeTrain(array([3., 4., 5.]) * ms, [0[13 chars]s])>' != "SpikeTrain\nname: 'train 1'\ndescription[59 chars]1.1}"
- <SpikeTrain(array([3., 4., 5.]) * ms, [0.5 ms, 10.0 ms])>
+ SpikeTrain
name: 'train 1'
description: 'a test object'
annotations: {'targ0': [1, 2], 'targ1': 1.1}

```

**Comment by JuliaSprenger** [comment]
This error occurs due to a new version of ipython and not due to a change in neo. It is working for ipython 6.1.0 but failing for 6.3.1.

**Comment by samuelgarcia** [comment]
ipython is involved in our test suite ?
Can we force a version of ipython for testing ?

**Comment by JuliaSprenger** [comment]
Ipython is what we support for pretty printing. We could force a version of ipython for testing, but I think it would be better to understand why ipython is yielding different results and adjust to that. No?

**Comment by samuelgarcia** [comment]
Yes and maybe support several version of ipython in the code for pretty.
AnalogSignala nd SpikeTrain don't have pretty ?

**Comment by samuelgarcia** [comment]
I guess your happiness descovering this new issue.
