### ISSUE TITLE
previously readable .smr is not readable anymore

### ISSUE THREAD

**Issue by grg2rsr** [NeuralEnsemble/python-neo#522]
I encountered a weird problem. I have `.smr` files which were definitely readable by `neo.io.Spike2IO` in the past (`python=2.7`, `neo=0.4`). If I attempt to read them now (`python=3.6`, `neo=0.6`) I can only get the events from the file, but no analogsignals.

The strange part is: the same files are not readable after downgrading to the old versions of neo and python, hence it might not even be directly neo related. I have a) no clue at all where to start looking around what else to downgrade, b) ask here if somebody has encountered something similar.

Thanks for help

**Comment by grg2rsr** [comment]
Some output of different versions:

`neo=0.6.1`, `python=3.6.5`
```
from neo import Spike2IO
In [3]: Spike2IO(filename='file.smr').read()
Out[3]: 
[Block with 1 segments
 annotations: {'system_id': 7}
 file_origin: 'file.smr'
 # segments (N=1)
 0: Segment with 2 events annotations: {'system_id': 7} # analogsignals (N=0)]
```

`neo=0.4.1`, `python=2.7.14`
```
>>> Spike2IO(filename='file.smr')
<neo.io.spike2io.Spike2IO object at 0x7fb1f3c56890>
>>> Spike2IO(filename='file.smr').read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/georg/anaconda3/envs/py27/lib/python2.7/site-packages/neo/io/baseio.py", line 121, in read
    seg = self.read_segment(lazy=lazy, cascade=cascade,  **kargs)
  File "/home/georg/anaconda3/envs/py27/lib/python2.7/site-packages/neo/io/spike2io.py", line 128, in read_segment
    anaSigs = self.readOneChannelContinuous( fid, i, header, take_ideal_sampling_rate, lazy = lazy)
  File "/home/georg/anaconda3/envs/py27/lib/python2.7/site-packages/neo/io/spike2io.py", line 255, in readOneChannelContinuous
    if channelHeader.unit in unit_convert:
  File "/home/georg/anaconda3/envs/py27/lib/python2.7/site-packages/neo/io/spike2io.py", line 472, in __getattr__
    return self.array[name][1:l+1]
TypeError: only integer scalar arrays can be converted to a scalar index
```

**Comment by grg2rsr** [comment]
[example file](https://depot.uni-konstanz.de/cgi-bin/exchange.pl?g=hpmadkvpeq )

**Comment by Huitzilo** [comment]
I ran into a very similar problem today. I can read analogsignals just fine from a file with v0.5.1, but in 0.6.1 I only see events (which were not present in v0.5.1).

Happy to share the file in private if it helps debugging.

**Comment by samuelgarcia** [comment]
Thank you for report this.
There was a string bug in spike2io since rawio (>0.6).
Sorry for that I am not a ced user so I did not see it.

I have make a patch here #527.

Could you test it  and compare to original signal you can see in spike2 (units/durations/amplitude...) ?

**Comment by Huitzilo** [comment]
Thanks for taking care of this! Unfortunately, the current version chokes on my .smr file (backtrace below). Let me know if you'd like to get your hands on the .smr file.

```
r = neo.io.Spike2IO(filename='my_smr_file.smr'))
r.read()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-23b9265ef61d> in <module>()
----> 1 r.read()

[...]/neo/io/baseio.py in read(self, lazy, **kargs)
    115                     callable(getattr(self, 'read_all_blocks'))):
    116                 return self.read_all_blocks(lazy=lazy, **kargs)
--> 117             return [self.read_block(lazy=lazy, **kargs)]
    118         elif Segment in self.readable_objects:
    119             bl = Block(name='One segment only')

[...]/neo/io/basefromrawio.py in read_block(self, block_index, lazy, signal_group_mode, units_group_mode, load_waveforms)
    180             seg = self.read_segment(block_index=block_index, seg_index=seg_index,
    181                                     lazy=lazy, signal_group_mode=signal_group_mode,
--> 182                                     load_waveforms=load_waveforms)
    183             bl.segments.append(seg)
    184 

[...]/neo/io/basefromrawio.py in read_segment(self, block_index, seg_index, lazy, signal_group_mode, load_waveforms, time_slice)
    272                 sr = self.get_signal_sampling_rate(channel_indexes) * pq.Hz
    273                 sig_t_start = self.get_signal_t_start(
--> 274                     block_index, seg_index, channel_indexes) * pq.s
    275 
    276                 sig_size = self.get_signal_size(block_index=block_index, seg_index=seg_index,

[...]/neo/rawio/baserawio.py in get_signal_t_start(self, block_index, seg_index, channel_indexes)
    463         if self._several_channel_groups:
    464             self._check_common_characteristics(channel_indexes)
--> 465         return self._get_signal_t_start(block_index, seg_index, channel_indexes)
    466 
    467     def get_signal_sampling_rate(self, channel_indexes=None):

[...]/neo/rawio/spike2rawio.py in _get_signal_t_start(self, block_index, seg_index, channel_indexes)
    317 
    318     def _get_signal_t_start(self, block_index, seg_index, channel_indexes):
--> 319         assert len(channel_indexes) == 1
    320         chan_id = self.header['signal_channels'][channel_indexes[0]]['id']
    321         return self._sig_t_starts[chan_id][seg_index] * self._time_factor

TypeError: object of type 'NoneType' has no len()
```

**Comment by Huitzilo** [comment]
Message sent off-list. Hope this helps!

**Comment by samuelgarcia** [comment]
I made a new commit.
It should be OK now.
Could test again ?

**Comment by Huitzilo** [comment]
Works for me with the latest commit! @grg2rsr ?

**Comment by samuelgarcia** [comment]
units/magnitude/samplerate/length  are OK ?

**Comment by Huitzilo** [comment]
Can't tell 100% about magnitude since I mainly care about the waveform (which looks good). Samplerate and length look fine, units too. BTW 0.5.1 didn't pick up the units, so that's an improvement!

**Comment by samuelgarcia** [comment]
Note that the main improvement is that is IO is much faster and you can read chunk chunk the raw data.
So you can read your dataset with [ephyviewer](http://ephyviewer.readthedocs.io).

**Comment by grg2rsr** [comment]
still doesn't work for me :( 
for complete `.smr` files I still get no analogsignals
```
In [15]: Spike2IO(filename='full.smr').read()
Out[15]: 
[Block with 1 segments
 annotations: {'system_id': 7}
 file_origin: 'full.smr'
 # segments (N=1)
 0: Segment with 2 events annotations: {'system_id': 7} # analogsignals (N=0)]
```

and for truncated files (where only a part of the entire recording was saved), I get
```
In [17]: Spike2IO(filename='161202_A_a_dts_dil2.smr').read()
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-17-604161b5c72e> in <module>()
----> 1 Spike2IO(filename='161202_A_a_dts_dil2.smr').read()

~/Dropbox/python/git_repos/neo_spike2io_fix/neo/io/spike2io.py in __init__(self, filename)
     10     def __init__(self, filename):
     11         Spike2RawIO.__init__(self, filename=filename)
---> 12         BaseFromRaw.__init__(self, filename)

~/Dropbox/python/git_repos/neo_spike2io_fix/neo/io/basefromrawio.py in __init__(self, *args, **kargs)
     71     def __init__(self, *args, **kargs):
     72         BaseIO.__init__(self, *args, **kargs)
---> 73         self.parse_header()
     74 
     75     def read_block(self, block_index=0, lazy=False, signal_group_mode=None,

~/Dropbox/python/git_repos/neo_spike2io_fix/neo/rawio/baserawio.py in parse_header(self)
    149 
    150         """
--> 151         self._parse_header()
    152         self._group_signal_channel_characteristics()
    153 

~/Dropbox/python/git_repos/neo_spike2io_fix/neo/rawio/spike2rawio.py in _parse_header(self)
     85                 else:
     86                     fid.seek(chan_info['firstblock'])
---> 87                     block_info = read_as_dict(fid, blockHeaderDesciption)
     88                     chan_info['t_start'] = block_info['start_time'] * \
     89                                            info['us_per_time'] * info['dtime_base']

~/Dropbox/python/git_repos/neo_spike2io_fix/neo/rawio/spike2rawio.py in read_as_dict(fid, dtype)
    532     """
    533     dt = np.dtype(dtype)
--> 534     h = np.fromstring(fid.read(dt.itemsize), dt)[0]
    535     info = OrderedDict()
    536     for k in dt.names:

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by samuelgarcia** [comment]
Strange.
With the file "161202_B_b_pob_dil3.smr" I have 2 signals.

Did you install the correct branch ?
```
pip uninstall neo
git clone https://github.com/samuelgarcia/python-neo.git
cd python-neo
git checkout fix_spike2_bug522
python setup.py develop
```

**Comment by grg2rsr** [comment]
sorry about that. I thought than when I am at the commit on the github page and click the clone button, I clone to the state with the commit. After explicitly checking out, all works. Thanks a lot!

**Comment by samuelgarcia** [comment]
No worry.
Happy that it work again in any situation.

Sorry for this stupid bug.
Porting many io to rawio last summer during a one-person-code-sprint lead to a big refactoring and so introduce some bugs.

So when #527 merge we can close this.
