### ISSUE TITLE
NixIO fails to write

### ISSUE THREAD

**Issue by grg2rsr** [NeuralEnsemble/python-neo#534]
I can't write data to disk using the NixIO.

```python
from neo import NixIO
from neo.core import Block
Blk = Block()
Writer = NixIO(filename='out.blk')
Writer.write_block(Blk)
```
produces

```shell
/home/georg/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Exception ignored in: <bound method NixIO.__del__ of <neo.io.nixio.NixIO object at 0x7ffb6795bb00>>
Traceback (most recent call last):
  File "/home/georg/Dropbox/python/SeqPeelSort/src/lib/neo/neo/io/nixio.py", line 1184, in __del__
  File "/home/georg/Dropbox/python/SeqPeelSort/src/lib/neo/neo/io/nixio.py", line 1176, in close
  File "/home/georg/anaconda3/lib/python3.6/site-packages/nixio/pycore/file.py", line 297, in close
  File "/home/georg/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 287, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
AttributeError: 'weakref' object has no attribute 'cline_in_traceback'
```
current verions:
```shell
$ pip show nixio
Name: nixio
Version: 1.4.5
Summary: Python bindings for NIX
Home-page: https://github.com/G-Node/nixpy
Author: Christian Kellner, Adrian Stoewer, Andrey Sobolev, Jan Grewe, Balint Morvai, Achilleas Koutsou
Author-email: dev@g-node.org
License: BSD
Location: /home/georg/anaconda3/lib/python3.6/site-packages
Requires: numpy, h5py
Required-by: 
```
 ```python
In [2]: neo.__version__
Out[2]: '0.7.0.dev'
```
```shell
$ conda list h5py
# packages in environment at /home/georg/anaconda3:
#
# Name                    Version                   Build  Channel
h5py                      2.7.1            py36h3585f63_0  
```

thanks for help

**Comment by grg2rsr** [comment]
thank you very much!
