### ISSUE TITLE
test_pynnio failing on CircleCI for Python 2.7

### ISSUE THREAD

**Issue by jpgill86** [NeuralEnsemble/python-neo#572]
After merging #565 into master (3694c07):

    ======================================================================
    FAIL: test_write_segment (neo.test.iotest.test_pynnio.TestPyNNNumpyIO_Spikes)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/circleci/repo/neo/test/iotest/test_pynnio.py", line 60, in test_write_segment
        assert_file_contents_equal(self.test_file, write_test_file)
      File "/home/circleci/repo/neo/test/tools.py", line 96, in assert_file_contents_equal
        assert file_digest(a) == file_digest(b), generate_error_message(a, b)
    AssertionError: Files have the same size but different contents

The test is failing on [CircleCI for Python 2.7](https://circleci.com/gh/NeuralEnsemble/python-neo/716). It's passing on [CircleCI for Python 3.6](https://circleci.com/gh/NeuralEnsemble/python-neo/717), and on [Travis](https://travis-ci.org/NeuralEnsemble/python-neo/builds/429532336).

**Comment by apdavison** [comment]
This test has been failing intermittently for months now, and I've been planning to remove the `PyNNIO` classes anyway, since PyNN now uses Neo directly rather than writing to its own format. I'll try to find time this week to take care of it.

**Comment by samuelgarcia** [comment]
>  for months now

years, in fact
